# -*- coding: utf-8 -*-
"""Testes Gerais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16p0KQogz4cKf4aPzuTBN7VgXUZL2OVzB

# Generating the table for the article
"""

from google.colab import drive

drive.mount('/content/gdrive')

root_path = '/content/gdrive/MyDrive/USP/Doutorado/PoliTO/Option Stopping/Codes/Implementation/optimal-stopping-cnn/Datasets/'
#/content/gdrive/MyDrive/USP/Doutorado/PoliTO/Option Stopping/Codes/Implementation/optimal-stopping-cnn/Datasets/BCE_train.csv

import pandas as pd
import numpy as np

symbols_list = ['BCE','VZ','T','IPG','DISH','ABEV','LEN','F','BTI','GPS','BP','COP','CVX','COG','LNG','ACNB','ORI','RE','AXP','C','DD','BHP','SCCO','OLN','MOS','INTC','HPQ','AMD','LOGI','ARW']

economic_sector = ['Communications','Communications','Communications','Communications','Communications','Consumer Discretionary','Consumer Discretionary','Consumer Discretionary','Consumer Discretionary','Consumer Discretionary','Energy','Energy','Energy','Energy','Energy','Financial','Financial','Financial','Financial','Financial','Materials','Materials','Materials','Materials','Materials','Technology','Technology','Technology','Technology','Technology']

symbol = 'BCE'
df_test = pd.read_csv(root_path+symbol+'_test.csv') 
df_train = pd.read_csv(root_path+symbol+'_train.csv')

print('Test size:' +str(len(df_test)))
print('Train size:' +str(len(df_train)))

from scipy.stats import skew
from scipy.stats import kurtosis
test = df_test['Close'].pct_change()

skew(test[1:])

"""## Creating the dataframe that will became the table"""

final_table = pd.DataFrame(columns = ['Economic Sector','Asset','Mean','Std','Skewness','Kurtosis','CNN Avg Payoff','LSMC Avg Payoff'])

final_table['Asset']=symbols_list
final_table['Economic Sector'] = economic_sector

final_table.head(3)

from scipy.stats import skew
from scipy.stats import kurtosis

list_means = []
list_std = []
list_skewness = []
list_kurtosis = []
for symbol in symbols_list:
  list_means.append(np.mean(pd.read_csv(root_path+symbol+'_test.csv')['Close'].pct_change()[1:]))
  list_std.append(np.std(pd.read_csv(root_path+symbol+'_test.csv')['Close'].pct_change()[1:]))
  list_skewness.append(skew(pd.read_csv(root_path+symbol+'_test.csv')['Close'].pct_change()[1:]))
  list_kurtosis.append(kurtosis(pd.read_csv(root_path+symbol+'_test.csv')['Close'].pct_change()[1:]))
final_table['Mean'] = list_means
final_table['Std'] = list_std
final_table['Skewness'] = list_skewness
final_table['Kurtosis'] = list_kurtosis

caption = 'Results with the returns statistics (mean, standard deviation, skewness, and kurtosis) and the respective results of our proposed model and the baseline (LSMC)'
print(final_table.to_latex(index=False,float_format="%.4f",label = 'tab:assets_result',caption=caption))

